### ISSUE TITLE
Search option filtering

### ISSUE THREAD

**Issue by willmcdonald** [ubyssey/salarydb#3]
Options that don't exist within the selected faculty or department aren't filtered out when one is selected

**Comment by blx** [comment]
What's one example @willmcdonald ?

**Comment by willmcdonald** [comment]
![screen shot 2015-12-09 at 2 51 21 pm](https://cloud.githubusercontent.com/assets/10147901/11701436/63062e04-9e84-11e5-9d9d-33c404ab9110.png)

**Comment by blx** [comment]
hmm gotcha. I'll look at this. right now the page template just has all those dropdown fields hardcoded so we would just need to make it ping the db for valid options given whatever existing constraints have been selected.
