### ISSUE TITLE
Convert PDF data to CSV

### ISSUE THREAD

**Issue by psiemens** [ubyssey/salarydb#5]
Unfortunately, the latest salary data (2015/16) is only available in PDF format: https://drive.google.com/open?id=0B4JErCL5dt7GQkk2XzFqVWFCQTA.

We need to parse this file and convert it to something that's easier to work with, ideally a CSV file.

PDFMiner looks like it could be promising: https://euske.github.io/pdfminer/

**Steps to take:**
1. Investigate how to parse PDF files (with Python or some other scripting language)
2. Convert the data in the above PDF into something that resembles this file: https://drive.google.com/open?id=0B4JErCL5dt7GNW15Q2FUdnRzZmM

**Comment by jimmyhli** [comment]
[salary1516.csv.xlsx](https://github.com/ubyssey/salarydb/files/749673/salary1516.csv.xlsx)
since github doesn't support csv so i uploaded it in xlsx, converting it to csv shud be easy though.. i only retrieved the info for 15-16 for your reference

**Comment by Cesium-Ice** [comment]
Well, I feel redundant now XD
